### PR TITLE
Test regression.

### PR DESCRIPTION
**Pull request by ioquatix**
Check if this test actually catch regressions: https://github.com/socketry/async-io/pull/70

## Types of Changes

- Maintenance.

## Contribution

- [ ] I added tests for my changes.
- [ ] I tested my changes locally.
- [ ] I agree to the [Developer's Certificate of Origin 1.1](https://developercertificate.org/).

### CODE REVIEW

**Comment by ioquatix** [comment]
@mintuhouse is there any chance you can make a test for this regression? Because it does not fail even with the previous code.

**Comment by mintuhouse** [comment]
https://github.com/socketry/async-io/pull/70/commits/9d0836ea8cf78e4e5c0750c2d89a5a03c7b74c23

The test in above commit fails without the fix in https://github.com/socketry/async-io/pull/70/commits/2328451b96234756d9def396c9bb363827f8a3ca

Is that what you are looking for?

**Comment by mintuhouse** [comment]
I am able to reproduce the test failure on devcontainer for ruby 3.2-bookworm
````
{
	"name": "Ruby",
	"image": "mcr.microsoft.com/devcontainers/ruby:1-3.2-bookworm"
}
````

**Comment by ioquatix** [comment]
I think the problem here is trying to create a unix socket on a bind mount filesystem within docker.

**Comment by ioquatix** [comment]
image

**Comment by ioquatix** [comment]
image

Both of those running in the docker image. Making IPC in a bind mount is definitely an issue.

**Comment by mintuhouse** [comment]
Does it mean supervisor may not be working in docker?
Will changing the ipc_path to `/tmp/supervisor.ipc` help?

**Comment by ioquatix** [comment]
Yes, I believe using a non-bind-mount path can help, but I don't know about whether IPC doesn't work on a bind mount. If you can test it, try using some of the supervisor commands, e.g. `falcon supervisor metrics` after using `falcon host` to start your app.

**Comment by mintuhouse** [comment]
`bundle exec falcon supervisor --path supervisor.sock metrics`  is working even though `ls -al` shows `s?????????`
Thanks for the help

**Pull request closed without merging**
